[tool.ruff]
extend-exclude = [ "pypi_template/templates", "docs" ]

[tool.coverage.run]
omit = [ "*/templates/*", "*/.tox/*", "*/distutils/*", "tests/*" ]

[tool.coverage.report]
omit = [ "*/templates/*", "*/.tox/*", "*/distutils/*", "tests/*" ]
